# Generated by Django 5.0 on 2024-03-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0004_gallery_rename_phonenumber_enrollment_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selectdate', models.DateTimeField(auto_now_add=True)),
                ('Login', models.CharField(max_length=200)),
                ('Logout', models.CharField(max_length=200)),
                ('SelctWorkout', models.CharField(max_length=200)),
                ('TrainedBy', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
