# Generated by Django 5.0 on 2024-03-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='phonenumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
