# Generated by Django 5.0 on 2024-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0006_attendance_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='SelctWorkout',
            new_name='SelectWorkout',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='TrainedBy',
            field=models.CharField(max_length=200),
        ),
    ]
